# This file was generated by GoReleaser. DO NOT EDIT.
cask "ww" do
  version "0.11.13"

  on_macos do
    on_intel do
      sha256 "c230ed096f2228d95207a833245281dcb338f8a3a050b9d7dc3da3b8ec49be06"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f7d7053c09e1c0be15a207bda6cc7d05dc4688cc8c42b276eb0f853258f16b8a"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "68c29fe2319f174d868cb8084aa9ac0f9bf0cec955d2d4bc1e282fe821708813"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "baae0c53358cceaeb1a14497b34ac1493f59fc263951530e2ee2bab4074eaf44"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ww"
  desc "witwave CLI for the Witwave multi-container agent platform"
  homepage "https://github.com/witwave-ai/witwave"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ww"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ww"]
    end
  end

  # No zap stanza required

end
