# This file was generated by GoReleaser. DO NOT EDIT.
cask "ww" do
  version "0.33.6"

  on_macos do
    on_intel do
      sha256 "04b637d7f92debfe3d18cddb08cfe64a0dce2b833f6a8c42038e513275a254d7"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5af5054f364152c5d4b07eb38649a9c3bc91bcd394a5502cdb48daacddcf1387"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7892e58723c82a97cc8424c4315bb96618b50a974af0ea7e46b4240424772650"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "12d4658d637b7d88732388d348a60d34380035411830b6e35c985dbca2552bc9"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ww"
  desc "witwave CLI for the Witwave multi-container agent platform"
  homepage "https://github.com/witwave-ai/witwave"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ww"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ww"]
    end
  end

  # No zap stanza required

end
