# This file was generated by GoReleaser. DO NOT EDIT.
cask "ww" do
  version "0.16.5"

  on_macos do
    on_intel do
      sha256 "b7ba74472d07d760b4945ba0728d5e62bc31434921044032aa3f7302d9e2106c"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f70ece15447b870fd483b6df32ccce0864cc9ba10cc3d56bacf65002ed1d106"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab2509601b6f5794925201e5fc849576113ffc4aa094636e2f31ad0b2ad89102"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b43944641b181357e658eefbb3c2c7eaa028242cd788fc210470f8b4cf49bdf1"
      url "https://github.com/witwave-ai/witwave/releases/download/v#{version}/ww_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ww"
  desc "witwave CLI for the Witwave multi-container agent platform"
  homepage "https://github.com/witwave-ai/witwave"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ww"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ww"]
    end
  end

  # No zap stanza required

end
