# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ww < Formula
  desc "witwave CLI for the Witwave multi-container agent platform"
  homepage "https://github.com/skthomasjr/witwave"
  version "0.4.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.4.3/ww_0.4.3_darwin_amd64.tar.gz"
      sha256 "02cfe25b6e798361aaca391e3a682e71c755e8fabff72d00f5284f1b6a71843f"

      define_method(:install) do
        bin.install "ww"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.4.3/ww_0.4.3_darwin_arm64.tar.gz"
      sha256 "a7f6fad57c5aaf91a0595b9f6b8c19d10ec04fe056f08759040f8042e4558192"

      define_method(:install) do
        bin.install "ww"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.4.3/ww_0.4.3_linux_amd64.tar.gz"
      sha256 "1a9ca7fe86b1f0a87422513992a2a9c80cc8973961acf6691c964f90487ec047"
      define_method(:install) do
        bin.install "ww"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.4.3/ww_0.4.3_linux_arm64.tar.gz"
      sha256 "3745b3f114afbf807c4aa18ac3df5dc7e3f98b1ac7bbae38e521d8275b595a69"
      define_method(:install) do
        bin.install "ww"
      end
    end
  end

  test do
    system "#{bin}/ww", "version"
  end
end
