# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ww < Formula
  desc "witwave CLI for the Witwave multi-container agent platform"
  homepage "https://github.com/skthomasjr/witwave"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.5.3/ww_0.5.3_darwin_amd64.tar.gz"
      sha256 "9a6c2d887ba2457b5205cbf6b22e970f848f7e7a03e7ef335f0e90c870dbe521"

      define_method(:install) do
        bin.install "ww"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.5.3/ww_0.5.3_darwin_arm64.tar.gz"
      sha256 "12d65b8ae7c333835175e9c69d0cf10fa5686a411a189469c089f58cad4b188d"

      define_method(:install) do
        bin.install "ww"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.5.3/ww_0.5.3_linux_amd64.tar.gz"
      sha256 "27e11f3f6e130f638d3d05ce5e7f7ea4f3c0b4ccabb94534b3d114b0f4911517"
      define_method(:install) do
        bin.install "ww"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.5.3/ww_0.5.3_linux_arm64.tar.gz"
      sha256 "e4399b84f40cf27eafd0a3742bdd65135d1fb9a0a63c5f215338bd3471dedb64"
      define_method(:install) do
        bin.install "ww"
      end
    end
  end

  test do
    system "#{bin}/ww", "version"
  end
end
