# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ww < Formula
  desc "witwave CLI for the Witwave multi-container agent platform"
  homepage "https://github.com/skthomasjr/witwave"
  version "0.5.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.5.8/ww_0.5.8_darwin_amd64.tar.gz"
      sha256 "185e64fb8a1fd6ec44b61f58b3d65aceba5c2901b3a692154ca4e192e3c58fac"

      define_method(:install) do
        bin.install "ww"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.5.8/ww_0.5.8_darwin_arm64.tar.gz"
      sha256 "23beda9e2a67c9b6144ad112fae65d21411c4cc1ec391c8176a303b3d6560d11"

      define_method(:install) do
        bin.install "ww"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.5.8/ww_0.5.8_linux_amd64.tar.gz"
      sha256 "0d22ee2aa0778673affe3fe48b015e853b9426bb042622dfbaa52698a0ffe816"
      define_method(:install) do
        bin.install "ww"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skthomasjr/witwave/releases/download/v0.5.8/ww_0.5.8_linux_arm64.tar.gz"
      sha256 "f970c9168df0c7742fcf4669a8b572475bfdab8a86d0ee74769dc385b807c213"
      define_method(:install) do
        bin.install "ww"
      end
    end
  end

  test do
    system "#{bin}/ww", "version"
  end
end
